[package]
name = "otp"
version = "0.1.5"
edition = "2021"

[dependencies]
# aes-gcm = "0.10.3"
# anyhow = "1.0.89"
argon2 = "0.5.3"
base64 = "0.22.1"
block-modes = "0.9.1"
block-padding = "0.3.3"
clap = "4.5.16"
openssl = "0.10.68"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
