[package]
name = "otp"
version = "0.2.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"
rand_chacha = "0.9.0"
rpassword = "7.4.0"
sha2 = "0.10.8"
