name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    # Regex for a version number such as v0.2.1,
    # or use - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    # - name: Create Tag
    #   run: |
    #     git config user.name "GitHub Actions"
    #     git config user.email "actions@github.com"
    #     git tag -a v1.0.0 -m "Release v1.0.0"
    #     git push origin v1.0.0

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/otp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
