name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    # Regex for a version number such as v0.2.1,
    # or use - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/otp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
