name: Build and Release

on:
  push:
    branches: [ "main" ]
    # tags:
    #   - 'v*'
    #   # Regex for a version number such as v0.2.1
    #   - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        # components: rustfmt, clippy
    
    # - name: Run tests
    #   run: cargo test

    - name: Build
      run: cargo build --release

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: otp
        path: target/release/otp
